### PR TITLE
More readable output in res.txt

### PR DESCRIPTION
**Pull request by AveryanAlex**
It is my second time I am coding Go, this code may contain stupid mistakes

### CODE REVIEW

**Comment by AveryanAlex** [comment]
https://github.com/StalkerMeyr/GUI-ygg_nice_ipv6.exe experimental python gui for ygg_me_nice_ipv6

**Comment by vikulin** [comment]
@averyanalex , could you please add appending write after app restart?

**Comment by AveryanAlex** [comment]
Do you mean after restart write to file ~3 blank lines, start time and arguments?
Start at 18:36 30.07 2020, maximum attemps: 100000, repeated bytes: 5

**Comment by vikulin** [comment]
No, result file is getting cleared up everytime app restarts

чт, 30 июл. 2020 г. в 18:38, Александр Аверьянов <notifications@github.com>:

**Comment by AveryanAlex** [comment]
Maybe generate new file? res-1.txt, res-2.txt and etc.

**Comment by vikulin** [comment]
why not to append new content?

пт, 31 июл. 2020 г. в 11:35, Александр Аверьянов <notifications@github.com>:

**Comment by AveryanAlex** [comment]
I cant uderstand you. Clean up file, generate new file, or store all in one file, but separate by blank lines and startup parametrs? I think generate new will be best solution

**Comment by vikulin** [comment]
Ok. I will complete it by myself.

пт, 31 июл. 2020 г. в 12:17, Александр Аверьянов <notifications@github.com>:

**Comment by AveryanAlex** [comment]
I will close this pull and open new, I refactored code, ok?

**Comment by vikulin** [comment]
ok

пт, 31 июл. 2020 г. в 14:18, Александр Аверьянов <notifications@github.com>:

**Pull request closed without merging**
